elastic/elastic-otel-python

- CHANGELOG.md
- CONTRIBUTING.md
- README.md
- pyproject.toml
Updates the official name of the distribution from "Elastic Distribution for OpenTelemetry" to "Elastic Distribution of OpenTelemetry".
> [docs] Update the official name of the distribution 

- .github/workflows/ci.yml
- README.md
- dev-requirements.txt
- pyproject.toml
- src/elasticotel/distro/__init__.py
- tests/distro/test_distro.py
- tests/integration/test_integration.py
Bump the opentelemetry dependency to latest to get:
- python 3.12 support
- non urlencoded authentication
- os resource detector (enabled by default)
Fixes #95
> Bump OTel upstream dependency to latest

- README.md
- docs/configure.md
- docs/get-started.md
Builds out minimal viable docs. At a minimum, distribution docs should answer all of the following questions:
- What is the product?
- Why would someone use the product?
- What problem does it solve?
- How does the product fit into the larger ecosystem?
- In this case, both the Elastic and OpenTelemetry ecosystems.
- Does the product have any dependencies?
- Where can the user acquire the product?
- If there are multiple options, provide guidance on how to choose the best approach.
- How does the user install the product?
- If there are multiple options, provide guidance on how to choose the best approach.
- What are the basic configuration options?
- How does the user set configuration options?
- What does a simple start-to-finish operation look like?
- Include a description of what the …
> [docs] Prepare minimal viable docs

- docs/configure.md
- src/elasticotel/distro/__init__.py
- tests/distro/test_distro.py
Cite that logs exporting is disabled by default and add a reference to the environment variable. While at it reorg a bit the content of the configuration options chapter.
> docs: cite configuration to enable logs exporting

- .github/workflows/ci.yml
- operator/Dockerfile
Add the musl based instrumentation to the image so that it can be used by the k8s operator once supports for using it is merged.
Closes #138
Refs #158
> operator: add musl based autoinstrumentation to docker image

- examples/flask/Dockerfile
- examples/flask/README.md
- examples/flask/app.py
Add a basic autoinstrumented flask app to have a working example around.
> Introduce examples dir with an autoinstrumented flask app

- operator/Dockerfile
Install g++ on musl because the docker build started failing on arm64 with:
```
File "/usr/local/lib/python3.12/subprocess.py", line 1955, in _execute_child
raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'c++'
```
See https://github.com/elastic/elastic-otel-python/actions/runs/11721354993/job/32648614646
> operator: install g++ on musl before installing requirements

- operator/Dockerfile
The instrumentation built is specific of the python version so we need to stick to 3.12 images.
While at it bump base image.
> operator: stick to python-3.12-dev image

- src/elasticotel/distro/__init__.py
Change the semantics of _OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED to only affect the setup of the OTel handler to the python logging module so that log events can be enabled by default.
Closes #152
> distro: enable log events by default

- operator/requirements.txt
Bump the version of our openai instrumentation in the docker image to the latest 0.4.0.
> operator: bump openai instrumentation version to 0.4.0

- src/elasticotel/distro/__init__.py
- tests/distro/test_distro.py
We have issues accepting Histograms that does not have DELTA temporality.
Closes #163
> distro: set OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE to DELTA

- CONTRIBUTING.md
- README.md
- docs/get-started.md
- docs/manual-instrumentation.md
- examples/flask/Dockerfile
- pyproject.toml
- scripts/build_edot_bootstrap_instrumentations.py
- src/elasticotel/instrumentation/bootstrap.py
- tests/instrumentation/test_bootstrap.py
Same opentelemetry-bootstrap but with our choices of instrumentations.
Refs #18
> Introduce edot-bootstrap

- README.md
- dev-requirements.txt
- pyproject.toml
- src/elasticotel/distro/__init__.py
- src/elasticotel/distro/resource_detectors.py
- tests/distro/test_distro.py
- tests/distro/test_resource_detectors.py
This add some code to dinamically filter the available resource detectors in order to avoid any eventual costly detection.
Closes #23
> distro: add cloud resource detectors

- operator/requirements.txt
- src/elasticotel/instrumentation/bootstrap.py
Bump elastic-opentelemetry-instrumentation-openai dependency to latest available.
> Bump elastic-opentelemetry-instrumentation-openai dependency to 0.6.0

- README.md
- dev-requirements.txt
- pyproject.toml
- src/elasticotel/distro/resource_detectors.py
- tests/distro/test_distro.py
- tests/distro/test_resource_detectors.py
Bump the AWS ones to a version that would not print warnings when loaded outside of the expected platform and disable the GCP one because it will go into an infinite loop on GCP.
Refs #198
> Revise cloud detectors

- .github/workflows/ci.yml
- operator/Dockerfile
The elastic docker registry is not available for forks of this repo or to dependabot so if you cannot use it use alternative upstream docker images.
> ci: use elastic registry only if available

- README.md
- docs/migrate-from-apm.md
Document some of the differences between the APM Python agent and EDOT.
Closes #123
> docs: add docs with differences from the APM Python agent

- src/elasticotel/distro/__init__.py
- tests/integration/test_integration.py
- tests/integration/utils.py
The custom code was introduced in 40ae8be2ff2672d345e19dc1edbc276969836035 for changing the semantics of the logs sdk. Since the semantic has been changed upstream too we can drop our custom code.
While at it add an integration test to check that events are emitted.
Closes #245
> distro: remove custom code in ElasticOpenTelemetryConfigurator

- README.md
- docs/configure.md
Move configuration bits that were in the README to docs/configure.md so we don't duplicate information.
Closes #249
> README: move configuration content to docs/configure.md

- docs/configure.md
- pyproject.toml
- src/elasticotel/distro/__init__.py
- src/elasticotel/sdk/resources/__init__.py
- tests/distro/test_distro.py
- tests/resources/test_resources.py
Introduce a resource detector sending a stringified UUIDv4 as value for `service.instance.id` attribute.
And enable it by default.
Closes #258
> resources: introduce a resource detector sending server.instance.id

- operator/requirements.txt
- src/elasticotel/instrumentation/bootstrap.py
So we can release the elastic openai instrumentation without requiring a release of EDOT.
While at it bump the elastic openai instrumentation version installed in the Dockerfile to latest.
> Relax openai instrumentation dependency in boostrap

- README.md
- docs/configure.md
- docs/troubleshooting.md
First stab at the troubleshooting page.
> docs: Add troubleshooting page

- operator/requirements.txt
Bump to latest release elastic-opentelemetry-instrumentation-openai in the operator image.
> operator: bump openai instrumentation to 1.0.0 in docker image

- .github/dependabot.yml
- renovate.json
Use `dependabot` for updating docker images stored in our internal docker registry using [this](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/configuring-access-to-private-registries-for-dependabot).
Use `directories` to manage the dependencies for the GitHub workflow sand composite actions.
We already have secrets stored for accessing the internal docker registry. Use one dependency management tool with native support for GitHub actions and the [GH secrets access control](https://github.blog/changelog/2021-02-19-github-actions-workflows-triggered-by-dependabot-prs-will-run-with-read-only-permissions/). 
This has been already tested in the past in a sandbox repository and also in another GH internal repositories.
See …
> dependabot: use directories and use docker ecosystem

- src/elasticotel/instrumentation/bootstrap.py
- tests/instrumentation/test_bootstrap.py
While it's still incomplete it's provided upstream and so enable it here too.
> bootstrap: enable vertexai instrumentation

- .github/renovate.json
Limit update to wolfi/python images to only patch releases because we want to stay on the same major.minor python version.
Refs #274
> renovate: limit update to python wolfi images only to patch releases

- src/elasticotel/distro/__init__.py
- tests/distro/test_distro.py
Otherwise the SDK will warn about empty string not being a float.
> distro: set OTEL_TRACES_SAMPLER_ARG to 1.0 by default

- src/elasticotel/distro/__init__.py
- src/elasticotel/distro/config.py
- tests/distro/test_distro.py
This will be available in stack 9.2.
> distro: handle dynamic tracing sampling rate from config

- src/elasticotel/distro/config.py
- src/opentelemetry/_opamp/client.py
- src/opentelemetry/_opamp/messages.py
- tests/distro/test_distro.py
- tests/opamp/README.md
- tests/opamp/cassettes/test_agent_send_full_state_when_asked.yaml
- tests/opamp/test_client.py
- tests/opamp/test_e2e.py
This adds support for handling the case where the server gets restarted and loses the state about the agent. Now the agent will act on the ReportFullState ServerToAgent flag being set and will resend the full configuration so that the server can rebuild its state.
This also introduces a very simplified handling of effective config.
Closes #357
> config: add handling of ReportFullState ServerToAgent flag

- docs/reference/edot-python/configuration.md
- src/elasticotel/distro/__init__.py
- src/elasticotel/distro/config.py
- src/elasticotel/distro/environment_variables.py
- tests/distro/test_distro.py
Introduces handling of ELASTIC_OTEL_LOG_LEVEL to change the log level of EDOT sdk using the same levels available from central configuration. While at it also fix default level :sweat: 
Fixes #378
> Handle log level change from environment variable

- docs/reference/edot-python/configuration.md
Add some applies_to annotations to recently added default configuration defaults.
> docs/configuration: add missing applies_to to default configuration
